<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>netstandard2.1</TargetFramework>
    </PropertyGroup>

    <ItemGroup>
      <Reference Include="0Harmony">
        <HintPath>..\..\..\.local\share\Steam\steamapps\common\Supermarket Together\BepInEx\core\0Harmony.dll</HintPath>
      </Reference>
      <Reference Include="Assembly-CSharp">
        <HintPath>..\..\..\.local\share\Steam\steamapps\common\Supermarket Together\Supermarket Together_Data\Managed\Assembly-CSharp.dll</HintPath>
      </Reference>
      <Reference Include="BepInEx">
        <HintPath>..\..\..\.local\share\Steam\steamapps\common\Supermarket Together\BepInEx\core\BepInEx.dll</HintPath>
      </Reference>
      <Reference Include="BepInEx.Harmony">
        <HintPath>..\..\..\.local\share\Steam\steamapps\common\Supermarket Together\BepInEx\core\BepInEx.Harmony.dll</HintPath>
      </Reference>
      <Reference Include="BepInEx.Preloader">
        <HintPath>..\..\..\.local\share\Steam\steamapps\common\Supermarket Together\BepInEx\core\BepInEx.Preloader.dll</HintPath>
      </Reference>
      <Reference Include="BouncyCastle.Cryptography">
        <HintPath>..\..\..\.local\share\Steam\steamapps\common\Supermarket Together\Supermarket Together_Data\Managed\BouncyCastle.Cryptography.dll</HintPath>
      </Reference>
      <Reference Include="CFXRRuntime">
        <HintPath>..\..\..\.local\share\Steam\steamapps\common\Supermarket Together\Supermarket Together_Data\Managed\CFXRRuntime.dll</HintPath>
      </Reference>
      <Reference Include="Cinemachine">
        <HintPath>..\..\..\.local\share\Steam\steamapps\common\Supermarket Together\Supermarket Together_Data\Managed\Cinemachine.dll</HintPath>
      </Reference>
      <Reference Include="com.rlabrecque.steamworks.net">
        <HintPath>..\..\..\.local\share\Steam\steamapps\common\Supermarket Together\Supermarket Together_Data\Managed\com.rlabrecque.steamworks.net.dll</HintPath>
      </Reference>
      <Reference Include="ConditionalExpression">
        <HintPath>..\..\..\.local\share\Steam\steamapps\common\Supermarket Together\Supermarket Together_Data\Managed\ConditionalExpression.dll</HintPath>
      </Reference>
      <Reference Include="DissonanceVoip">
        <HintPath>..\..\..\.local\share\Steam\steamapps\common\Supermarket Together\Supermarket Together_Data\Managed\DissonanceVoip.dll</HintPath>
      </Reference>
      <Reference Include="FizzySteamworks">
        <HintPath>..\..\..\.local\share\Steam\steamapps\common\Supermarket Together\Supermarket Together_Data\Managed\FizzySteamworks.dll</HintPath>
      </Reference>
      <Reference Include="HarmonyXInterop">
        <HintPath>..\..\..\.local\share\Steam\steamapps\common\Supermarket Together\BepInEx\core\HarmonyXInterop.dll</HintPath>
      </Reference>
      <Reference Include="kcp2k">
        <HintPath>..\..\..\.local\share\Steam\steamapps\common\Supermarket Together\Supermarket Together_Data\Managed\kcp2k.dll</HintPath>
      </Reference>
      <Reference Include="MeshCombinerCore">
        <HintPath>..\..\..\.local\share\Steam\steamapps\common\Supermarket Together\Supermarket Together_Data\Managed\MeshCombinerCore.dll</HintPath>
      </Reference>
      <Reference Include="MeshCombinerDemo">
        <HintPath>..\..\..\.local\share\Steam\steamapps\common\Supermarket Together\Supermarket Together_Data\Managed\MeshCombinerDemo.dll</HintPath>
      </Reference>
      <Reference Include="Mirror">
        <HintPath>..\..\..\.local\share\Steam\steamapps\common\Supermarket Together\Supermarket Together_Data\Managed\Mirror.dll</HintPath>
      </Reference>
      <Reference Include="Mirror.Authenticators">
        <HintPath>..\..\..\.local\share\Steam\steamapps\common\Supermarket Together\Supermarket Together_Data\Managed\Mirror.Authenticators.dll</HintPath>
      </Reference>
      <Reference Include="Mirror.Components">
        <HintPath>..\..\..\.local\share\Steam\steamapps\common\Supermarket Together\Supermarket Together_Data\Managed\Mirror.Components.dll</HintPath>
      </Reference>
      <Reference Include="Mirror.Examples">
        <HintPath>..\..\..\.local\share\Steam\steamapps\common\Supermarket Together\Supermarket Together_Data\Managed\Mirror.Examples.dll</HintPath>
      </Reference>
      <Reference Include="Mirror.Transports">
        <HintPath>..\..\..\.local\share\Steam\steamapps\common\Supermarket Together\Supermarket Together_Data\Managed\Mirror.Transports.dll</HintPath>
      </Reference>
      <Reference Include="Mono.Cecil">
        <HintPath>..\..\..\.local\share\Steam\steamapps\common\Supermarket Together\BepInEx\core\Mono.Cecil.dll</HintPath>
      </Reference>
      <Reference Include="Mono.Cecil.Mdb">
        <HintPath>..\..\..\.local\share\Steam\steamapps\common\Supermarket Together\BepInEx\core\Mono.Cecil.Mdb.dll</HintPath>
      </Reference>
      <Reference Include="Mono.Cecil.Pdb">
        <HintPath>..\..\..\.local\share\Steam\steamapps\common\Supermarket Together\BepInEx\core\Mono.Cecil.Pdb.dll</HintPath>
      </Reference>
      <Reference Include="Mono.Cecil.Rocks">
        <HintPath>..\..\..\.local\share\Steam\steamapps\common\Supermarket Together\BepInEx\core\Mono.Cecil.Rocks.dll</HintPath>
      </Reference>
      <Reference Include="MonoMod.RuntimeDetour">
        <HintPath>..\..\..\.local\share\Steam\steamapps\common\Supermarket Together\BepInEx\core\MonoMod.RuntimeDetour.dll</HintPath>
      </Reference>
      <Reference Include="MonoMod.Utils">
        <HintPath>..\..\..\.local\share\Steam\steamapps\common\Supermarket Together\BepInEx\core\MonoMod.Utils.dll</HintPath>
      </Reference>
      <Reference Include="Newtonsoft.Json">
        <HintPath>..\..\..\.local\share\Steam\steamapps\common\Supermarket Together\Supermarket Together_Data\Managed\Newtonsoft.Json.dll</HintPath>
      </Reference>
      <Reference Include="PlayMaker">
        <HintPath>..\..\..\.local\share\Steam\steamapps\common\Supermarket Together\Supermarket Together_Data\Managed\PlayMaker.dll</HintPath>
      </Reference>
      <Reference Include="Rewired_Core">
        <HintPath>..\..\..\.local\share\Steam\steamapps\common\Supermarket Together\Supermarket Together_Data\Managed\Rewired_Core.dll</HintPath>
      </Reference>
      <Reference Include="Rewired_Windows">
        <HintPath>..\..\..\.local\share\Steam\steamapps\common\Supermarket Together\Supermarket Together_Data\Managed\Rewired_Windows.dll</HintPath>
      </Reference>
      <Reference Include="SimpleWebTransport">
        <HintPath>..\..\..\.local\share\Steam\steamapps\common\Supermarket Together\Supermarket Together_Data\Managed\SimpleWebTransport.dll</HintPath>
      </Reference>
      <Reference Include="Telepathy">
        <HintPath>..\..\..\.local\share\Steam\steamapps\common\Supermarket Together\Supermarket Together_Data\Managed\Telepathy.dll</HintPath>
      </Reference>
      <Reference Include="UModelerCommon">
        <HintPath>..\..\..\.local\share\Steam\steamapps\common\Supermarket Together\Supermarket Together_Data\Managed\UModelerCommon.dll</HintPath>
      </Reference>
      <Reference Include="Unity.AI.Navigation">
        <HintPath>..\..\..\.local\share\Steam\steamapps\common\Supermarket Together\Supermarket Together_Data\Managed\Unity.AI.Navigation.dll</HintPath>
      </Reference>
      <Reference Include="Unity.Animation.Rigging">
        <HintPath>..\..\..\.local\share\Steam\steamapps\common\Supermarket Together\Supermarket Together_Data\Managed\Unity.Animation.Rigging.dll</HintPath>
      </Reference>
      <Reference Include="Unity.Animation.Rigging.DocCodeExamples">
        <HintPath>..\..\..\.local\share\Steam\steamapps\common\Supermarket Together\Supermarket Together_Data\Managed\Unity.Animation.Rigging.DocCodeExamples.dll</HintPath>
      </Reference>
      <Reference Include="Unity.Burst">
        <HintPath>..\..\..\.local\share\Steam\steamapps\common\Supermarket Together\Supermarket Together_Data\Managed\Unity.Burst.dll</HintPath>
      </Reference>
      <Reference Include="Unity.Burst.Unsafe">
        <HintPath>..\..\..\.local\share\Steam\steamapps\common\Supermarket Together\Supermarket Together_Data\Managed\Unity.Burst.Unsafe.dll</HintPath>
      </Reference>
      <Reference Include="Unity.InputSystem">
        <HintPath>..\..\..\.local\share\Steam\steamapps\common\Supermarket Together\Supermarket Together_Data\Managed\Unity.InputSystem.dll</HintPath>
      </Reference>
      <Reference Include="Unity.InputSystem.ForUI">
        <HintPath>..\..\..\.local\share\Steam\steamapps\common\Supermarket Together\Supermarket Together_Data\Managed\Unity.InputSystem.ForUI.dll</HintPath>
      </Reference>
      <Reference Include="Unity.Mathematics">
        <HintPath>..\..\..\.local\share\Steam\steamapps\common\Supermarket Together\Supermarket Together_Data\Managed\Unity.Mathematics.dll</HintPath>
      </Reference>
      <Reference Include="Unity.MemoryProfiler">
        <HintPath>..\..\..\.local\share\Steam\steamapps\common\Supermarket Together\Supermarket Together_Data\Managed\Unity.MemoryProfiler.dll</HintPath>
      </Reference>
      <Reference Include="Unity.Profiling.Core">
        <HintPath>..\..\..\.local\share\Steam\steamapps\common\Supermarket Together\Supermarket Together_Data\Managed\Unity.Profiling.Core.dll</HintPath>
      </Reference>
      <Reference Include="Unity.RenderPipeline.Universal.ShaderLibrary">
        <HintPath>..\..\..\.local\share\Steam\steamapps\common\Supermarket Together\Supermarket Together_Data\Managed\Unity.RenderPipeline.Universal.ShaderLibrary.dll</HintPath>
      </Reference>
      <Reference Include="Unity.RenderPipelines.Core.Runtime">
        <HintPath>..\..\..\.local\share\Steam\steamapps\common\Supermarket Together\Supermarket Together_Data\Managed\Unity.RenderPipelines.Core.Runtime.dll</HintPath>
      </Reference>
      <Reference Include="Unity.RenderPipelines.Core.ShaderLibrary">
        <HintPath>..\..\..\.local\share\Steam\steamapps\common\Supermarket Together\Supermarket Together_Data\Managed\Unity.RenderPipelines.Core.ShaderLibrary.dll</HintPath>
      </Reference>
      <Reference Include="Unity.RenderPipelines.ShaderGraph.ShaderGraphLibrary">
        <HintPath>..\..\..\.local\share\Steam\steamapps\common\Supermarket Together\Supermarket Together_Data\Managed\Unity.RenderPipelines.ShaderGraph.ShaderGraphLibrary.dll</HintPath>
      </Reference>
      <Reference Include="Unity.RenderPipelines.Universal.2D.Runtime">
        <HintPath>..\..\..\.local\share\Steam\steamapps\common\Supermarket Together\Supermarket Together_Data\Managed\Unity.RenderPipelines.Universal.2D.Runtime.dll</HintPath>
      </Reference>
      <Reference Include="Unity.RenderPipelines.Universal.Runtime">
        <HintPath>..\..\..\.local\share\Steam\steamapps\common\Supermarket Together\Supermarket Together_Data\Managed\Unity.RenderPipelines.Universal.Runtime.dll</HintPath>
      </Reference>
      <Reference Include="Unity.RenderPipelines.Universal.Shaders">
        <HintPath>..\..\..\.local\share\Steam\steamapps\common\Supermarket Together\Supermarket Together_Data\Managed\Unity.RenderPipelines.Universal.Shaders.dll</HintPath>
      </Reference>
      <Reference Include="Unity.StarterAssets">
        <HintPath>..\..\..\.local\share\Steam\steamapps\common\Supermarket Together\Supermarket Together_Data\Managed\Unity.StarterAssets.dll</HintPath>
      </Reference>
      <Reference Include="Unity.TextMeshPro">
        <HintPath>..\..\..\.local\share\Steam\steamapps\common\Supermarket Together\Supermarket Together_Data\Managed\Unity.TextMeshPro.dll</HintPath>
      </Reference>
      <Reference Include="Unity.Timeline">
        <HintPath>..\..\..\.local\share\Steam\steamapps\common\Supermarket Together\Supermarket Together_Data\Managed\Unity.Timeline.dll</HintPath>
      </Reference>
      <Reference Include="Unity.VisualScripting.Antlr3.Runtime">
        <HintPath>..\..\..\.local\share\Steam\steamapps\common\Supermarket Together\Supermarket Together_Data\Managed\Unity.VisualScripting.Antlr3.Runtime.dll</HintPath>
      </Reference>
      <Reference Include="Unity.VisualScripting.Core">
        <HintPath>..\..\..\.local\share\Steam\steamapps\common\Supermarket Together\Supermarket Together_Data\Managed\Unity.VisualScripting.Core.dll</HintPath>
      </Reference>
      <Reference Include="Unity.VisualScripting.Flow">
        <HintPath>..\..\..\.local\share\Steam\steamapps\common\Supermarket Together\Supermarket Together_Data\Managed\Unity.VisualScripting.Flow.dll</HintPath>
      </Reference>
      <Reference Include="Unity.VisualScripting.State">
        <HintPath>..\..\..\.local\share\Steam\steamapps\common\Supermarket Together\Supermarket Together_Data\Managed\Unity.VisualScripting.State.dll</HintPath>
      </Reference>
      <Reference Include="UnityEngine">
        <HintPath>..\..\..\.local\share\Steam\steamapps\common\Supermarket Together\Supermarket Together_Data\Managed\UnityEngine.dll</HintPath>
      </Reference>
      <Reference Include="UnityEngine.AccessibilityModule">
        <HintPath>..\..\..\.local\share\Steam\steamapps\common\Supermarket Together\Supermarket Together_Data\Managed\UnityEngine.AccessibilityModule.dll</HintPath>
      </Reference>
      <Reference Include="UnityEngine.AIModule">
        <HintPath>..\..\..\.local\share\Steam\steamapps\common\Supermarket Together\Supermarket Together_Data\Managed\UnityEngine.AIModule.dll</HintPath>
      </Reference>
      <Reference Include="UnityEngine.AndroidJNIModule">
        <HintPath>..\..\..\.local\share\Steam\steamapps\common\Supermarket Together\Supermarket Together_Data\Managed\UnityEngine.AndroidJNIModule.dll</HintPath>
      </Reference>
      <Reference Include="UnityEngine.AnimationModule">
        <HintPath>..\..\..\.local\share\Steam\steamapps\common\Supermarket Together\Supermarket Together_Data\Managed\UnityEngine.AnimationModule.dll</HintPath>
      </Reference>
      <Reference Include="UnityEngine.ARModule">
        <HintPath>..\..\..\.local\share\Steam\steamapps\common\Supermarket Together\Supermarket Together_Data\Managed\UnityEngine.ARModule.dll</HintPath>
      </Reference>
      <Reference Include="UnityEngine.AssetBundleModule">
        <HintPath>..\..\..\.local\share\Steam\steamapps\common\Supermarket Together\Supermarket Together_Data\Managed\UnityEngine.AssetBundleModule.dll</HintPath>
      </Reference>
      <Reference Include="UnityEngine.AudioModule">
        <HintPath>..\..\..\.local\share\Steam\steamapps\common\Supermarket Together\Supermarket Together_Data\Managed\UnityEngine.AudioModule.dll</HintPath>
      </Reference>
      <Reference Include="UnityEngine.ClothModule">
        <HintPath>..\..\..\.local\share\Steam\steamapps\common\Supermarket Together\Supermarket Together_Data\Managed\UnityEngine.ClothModule.dll</HintPath>
      </Reference>
      <Reference Include="UnityEngine.ClusterInputModule">
        <HintPath>..\..\..\.local\share\Steam\steamapps\common\Supermarket Together\Supermarket Together_Data\Managed\UnityEngine.ClusterInputModule.dll</HintPath>
      </Reference>
      <Reference Include="UnityEngine.ClusterRendererModule">
        <HintPath>..\..\..\.local\share\Steam\steamapps\common\Supermarket Together\Supermarket Together_Data\Managed\UnityEngine.ClusterRendererModule.dll</HintPath>
      </Reference>
      <Reference Include="UnityEngine.CommandStateObserverModule">
        <HintPath>..\..\..\.local\share\Steam\steamapps\common\Supermarket Together\Supermarket Together_Data\Managed\UnityEngine.CommandStateObserverModule.dll</HintPath>
      </Reference>
      <Reference Include="UnityEngine.ContentLoadModule">
        <HintPath>..\..\..\.local\share\Steam\steamapps\common\Supermarket Together\Supermarket Together_Data\Managed\UnityEngine.ContentLoadModule.dll</HintPath>
      </Reference>
      <Reference Include="UnityEngine.CoreModule">
        <HintPath>..\..\..\.local\share\Steam\steamapps\common\Supermarket Together\Supermarket Together_Data\Managed\UnityEngine.CoreModule.dll</HintPath>
      </Reference>
      <Reference Include="UnityEngine.CrashReportingModule">
        <HintPath>..\..\..\.local\share\Steam\steamapps\common\Supermarket Together\Supermarket Together_Data\Managed\UnityEngine.CrashReportingModule.dll</HintPath>
      </Reference>
      <Reference Include="UnityEngine.DirectorModule">
        <HintPath>..\..\..\.local\share\Steam\steamapps\common\Supermarket Together\Supermarket Together_Data\Managed\UnityEngine.DirectorModule.dll</HintPath>
      </Reference>
      <Reference Include="UnityEngine.DSPGraphModule">
        <HintPath>..\..\..\.local\share\Steam\steamapps\common\Supermarket Together\Supermarket Together_Data\Managed\UnityEngine.DSPGraphModule.dll</HintPath>
      </Reference>
      <Reference Include="UnityEngine.GameCenterModule">
        <HintPath>..\..\..\.local\share\Steam\steamapps\common\Supermarket Together\Supermarket Together_Data\Managed\UnityEngine.GameCenterModule.dll</HintPath>
      </Reference>
      <Reference Include="UnityEngine.GIModule">
        <HintPath>..\..\..\.local\share\Steam\steamapps\common\Supermarket Together\Supermarket Together_Data\Managed\UnityEngine.GIModule.dll</HintPath>
      </Reference>
      <Reference Include="UnityEngine.GraphToolsFoundationModule">
        <HintPath>..\..\..\.local\share\Steam\steamapps\common\Supermarket Together\Supermarket Together_Data\Managed\UnityEngine.GraphToolsFoundationModule.dll</HintPath>
      </Reference>
      <Reference Include="UnityEngine.GridModule">
        <HintPath>..\..\..\.local\share\Steam\steamapps\common\Supermarket Together\Supermarket Together_Data\Managed\UnityEngine.GridModule.dll</HintPath>
      </Reference>
      <Reference Include="UnityEngine.HotReloadModule">
        <HintPath>..\..\..\.local\share\Steam\steamapps\common\Supermarket Together\Supermarket Together_Data\Managed\UnityEngine.HotReloadModule.dll</HintPath>
      </Reference>
      <Reference Include="UnityEngine.ImageConversionModule">
        <HintPath>..\..\..\.local\share\Steam\steamapps\common\Supermarket Together\Supermarket Together_Data\Managed\UnityEngine.ImageConversionModule.dll</HintPath>
      </Reference>
      <Reference Include="UnityEngine.IMGUIModule">
        <HintPath>..\..\..\.local\share\Steam\steamapps\common\Supermarket Together\Supermarket Together_Data\Managed\UnityEngine.IMGUIModule.dll</HintPath>
      </Reference>
      <Reference Include="UnityEngine.InputLegacyModule">
        <HintPath>..\..\..\.local\share\Steam\steamapps\common\Supermarket Together\Supermarket Together_Data\Managed\UnityEngine.InputLegacyModule.dll</HintPath>
      </Reference>
      <Reference Include="UnityEngine.InputModule">
        <HintPath>..\..\..\.local\share\Steam\steamapps\common\Supermarket Together\Supermarket Together_Data\Managed\UnityEngine.InputModule.dll</HintPath>
      </Reference>
      <Reference Include="UnityEngine.JSONSerializeModule">
        <HintPath>..\..\..\.local\share\Steam\steamapps\common\Supermarket Together\Supermarket Together_Data\Managed\UnityEngine.JSONSerializeModule.dll</HintPath>
      </Reference>
      <Reference Include="UnityEngine.LocalizationModule">
        <HintPath>..\..\..\.local\share\Steam\steamapps\common\Supermarket Together\Supermarket Together_Data\Managed\UnityEngine.LocalizationModule.dll</HintPath>
      </Reference>
      <Reference Include="UnityEngine.MarshallingModule">
        <HintPath>..\..\..\.local\share\Steam\steamapps\common\Supermarket Together\Supermarket Together_Data\Managed\UnityEngine.MarshallingModule.dll</HintPath>
      </Reference>
      <Reference Include="UnityEngine.NVIDIAModule">
        <HintPath>..\..\..\.local\share\Steam\steamapps\common\Supermarket Together\Supermarket Together_Data\Managed\UnityEngine.NVIDIAModule.dll</HintPath>
      </Reference>
      <Reference Include="UnityEngine.ParticleSystemModule">
        <HintPath>..\..\..\.local\share\Steam\steamapps\common\Supermarket Together\Supermarket Together_Data\Managed\UnityEngine.ParticleSystemModule.dll</HintPath>
      </Reference>
      <Reference Include="UnityEngine.PerformanceReportingModule">
        <HintPath>..\..\..\.local\share\Steam\steamapps\common\Supermarket Together\Supermarket Together_Data\Managed\UnityEngine.PerformanceReportingModule.dll</HintPath>
      </Reference>
      <Reference Include="UnityEngine.Physics2DModule">
        <HintPath>..\..\..\.local\share\Steam\steamapps\common\Supermarket Together\Supermarket Together_Data\Managed\UnityEngine.Physics2DModule.dll</HintPath>
      </Reference>
      <Reference Include="UnityEngine.PhysicsModule">
        <HintPath>..\..\..\.local\share\Steam\steamapps\common\Supermarket Together\Supermarket Together_Data\Managed\UnityEngine.PhysicsModule.dll</HintPath>
      </Reference>
      <Reference Include="UnityEngine.ProfilerModule">
        <HintPath>..\..\..\.local\share\Steam\steamapps\common\Supermarket Together\Supermarket Together_Data\Managed\UnityEngine.ProfilerModule.dll</HintPath>
      </Reference>
      <Reference Include="UnityEngine.PropertiesModule">
        <HintPath>..\..\..\.local\share\Steam\steamapps\common\Supermarket Together\Supermarket Together_Data\Managed\UnityEngine.PropertiesModule.dll</HintPath>
      </Reference>
      <Reference Include="UnityEngine.RuntimeInitializeOnLoadManagerInitializerModule">
        <HintPath>..\..\..\.local\share\Steam\steamapps\common\Supermarket Together\Supermarket Together_Data\Managed\UnityEngine.RuntimeInitializeOnLoadManagerInitializerModule.dll</HintPath>
      </Reference>
      <Reference Include="UnityEngine.ScreenCaptureModule">
        <HintPath>..\..\..\.local\share\Steam\steamapps\common\Supermarket Together\Supermarket Together_Data\Managed\UnityEngine.ScreenCaptureModule.dll</HintPath>
      </Reference>
      <Reference Include="UnityEngine.SharedInternalsModule">
        <HintPath>..\..\..\.local\share\Steam\steamapps\common\Supermarket Together\Supermarket Together_Data\Managed\UnityEngine.SharedInternalsModule.dll</HintPath>
      </Reference>
      <Reference Include="UnityEngine.SpriteMaskModule">
        <HintPath>..\..\..\.local\share\Steam\steamapps\common\Supermarket Together\Supermarket Together_Data\Managed\UnityEngine.SpriteMaskModule.dll</HintPath>
      </Reference>
      <Reference Include="UnityEngine.SpriteShapeModule">
        <HintPath>..\..\..\.local\share\Steam\steamapps\common\Supermarket Together\Supermarket Together_Data\Managed\UnityEngine.SpriteShapeModule.dll</HintPath>
      </Reference>
      <Reference Include="UnityEngine.StreamingModule">
        <HintPath>..\..\..\.local\share\Steam\steamapps\common\Supermarket Together\Supermarket Together_Data\Managed\UnityEngine.StreamingModule.dll</HintPath>
      </Reference>
      <Reference Include="UnityEngine.SubstanceModule">
        <HintPath>..\..\..\.local\share\Steam\steamapps\common\Supermarket Together\Supermarket Together_Data\Managed\UnityEngine.SubstanceModule.dll</HintPath>
      </Reference>
      <Reference Include="UnityEngine.SubsystemsModule">
        <HintPath>..\..\..\.local\share\Steam\steamapps\common\Supermarket Together\Supermarket Together_Data\Managed\UnityEngine.SubsystemsModule.dll</HintPath>
      </Reference>
      <Reference Include="UnityEngine.TerrainModule">
        <HintPath>..\..\..\.local\share\Steam\steamapps\common\Supermarket Together\Supermarket Together_Data\Managed\UnityEngine.TerrainModule.dll</HintPath>
      </Reference>
      <Reference Include="UnityEngine.TerrainPhysicsModule">
        <HintPath>..\..\..\.local\share\Steam\steamapps\common\Supermarket Together\Supermarket Together_Data\Managed\UnityEngine.TerrainPhysicsModule.dll</HintPath>
      </Reference>
      <Reference Include="UnityEngine.TextCoreFontEngineModule">
        <HintPath>..\..\..\.local\share\Steam\steamapps\common\Supermarket Together\Supermarket Together_Data\Managed\UnityEngine.TextCoreFontEngineModule.dll</HintPath>
      </Reference>
      <Reference Include="UnityEngine.TextCoreTextEngineModule">
        <HintPath>..\..\..\.local\share\Steam\steamapps\common\Supermarket Together\Supermarket Together_Data\Managed\UnityEngine.TextCoreTextEngineModule.dll</HintPath>
      </Reference>
      <Reference Include="UnityEngine.TextRenderingModule">
        <HintPath>..\..\..\.local\share\Steam\steamapps\common\Supermarket Together\Supermarket Together_Data\Managed\UnityEngine.TextRenderingModule.dll</HintPath>
      </Reference>
      <Reference Include="UnityEngine.TilemapModule">
        <HintPath>..\..\..\.local\share\Steam\steamapps\common\Supermarket Together\Supermarket Together_Data\Managed\UnityEngine.TilemapModule.dll</HintPath>
      </Reference>
      <Reference Include="UnityEngine.TLSModule">
        <HintPath>..\..\..\.local\share\Steam\steamapps\common\Supermarket Together\Supermarket Together_Data\Managed\UnityEngine.TLSModule.dll</HintPath>
      </Reference>
      <Reference Include="UnityEngine.UI">
        <HintPath>..\..\..\.local\share\Steam\steamapps\common\Supermarket Together\Supermarket Together_Data\Managed\UnityEngine.UI.dll</HintPath>
      </Reference>
      <Reference Include="UnityEngine.UIElementsModule">
        <HintPath>..\..\..\.local\share\Steam\steamapps\common\Supermarket Together\Supermarket Together_Data\Managed\UnityEngine.UIElementsModule.dll</HintPath>
      </Reference>
      <Reference Include="UnityEngine.UIModule">
        <HintPath>..\..\..\.local\share\Steam\steamapps\common\Supermarket Together\Supermarket Together_Data\Managed\UnityEngine.UIModule.dll</HintPath>
      </Reference>
      <Reference Include="UnityEngine.UmbraModule">
        <HintPath>..\..\..\.local\share\Steam\steamapps\common\Supermarket Together\Supermarket Together_Data\Managed\UnityEngine.UmbraModule.dll</HintPath>
      </Reference>
      <Reference Include="UnityEngine.UnityAnalyticsCommonModule">
        <HintPath>..\..\..\.local\share\Steam\steamapps\common\Supermarket Together\Supermarket Together_Data\Managed\UnityEngine.UnityAnalyticsCommonModule.dll</HintPath>
      </Reference>
      <Reference Include="UnityEngine.UnityAnalyticsModule">
        <HintPath>..\..\..\.local\share\Steam\steamapps\common\Supermarket Together\Supermarket Together_Data\Managed\UnityEngine.UnityAnalyticsModule.dll</HintPath>
      </Reference>
      <Reference Include="UnityEngine.UnityConnectModule">
        <HintPath>..\..\..\.local\share\Steam\steamapps\common\Supermarket Together\Supermarket Together_Data\Managed\UnityEngine.UnityConnectModule.dll</HintPath>
      </Reference>
      <Reference Include="UnityEngine.UnityCurlModule">
        <HintPath>..\..\..\.local\share\Steam\steamapps\common\Supermarket Together\Supermarket Together_Data\Managed\UnityEngine.UnityCurlModule.dll</HintPath>
      </Reference>
      <Reference Include="UnityEngine.UnityTestProtocolModule">
        <HintPath>..\..\..\.local\share\Steam\steamapps\common\Supermarket Together\Supermarket Together_Data\Managed\UnityEngine.UnityTestProtocolModule.dll</HintPath>
      </Reference>
      <Reference Include="UnityEngine.UnityWebRequestAssetBundleModule">
        <HintPath>..\..\..\.local\share\Steam\steamapps\common\Supermarket Together\Supermarket Together_Data\Managed\UnityEngine.UnityWebRequestAssetBundleModule.dll</HintPath>
      </Reference>
      <Reference Include="UnityEngine.UnityWebRequestAudioModule">
        <HintPath>..\..\..\.local\share\Steam\steamapps\common\Supermarket Together\Supermarket Together_Data\Managed\UnityEngine.UnityWebRequestAudioModule.dll</HintPath>
      </Reference>
      <Reference Include="UnityEngine.UnityWebRequestModule">
        <HintPath>..\..\..\.local\share\Steam\steamapps\common\Supermarket Together\Supermarket Together_Data\Managed\UnityEngine.UnityWebRequestModule.dll</HintPath>
      </Reference>
      <Reference Include="UnityEngine.UnityWebRequestTextureModule">
        <HintPath>..\..\..\.local\share\Steam\steamapps\common\Supermarket Together\Supermarket Together_Data\Managed\UnityEngine.UnityWebRequestTextureModule.dll</HintPath>
      </Reference>
      <Reference Include="UnityEngine.UnityWebRequestWWWModule">
        <HintPath>..\..\..\.local\share\Steam\steamapps\common\Supermarket Together\Supermarket Together_Data\Managed\UnityEngine.UnityWebRequestWWWModule.dll</HintPath>
      </Reference>
      <Reference Include="UnityEngine.VehiclesModule">
        <HintPath>..\..\..\.local\share\Steam\steamapps\common\Supermarket Together\Supermarket Together_Data\Managed\UnityEngine.VehiclesModule.dll</HintPath>
      </Reference>
      <Reference Include="UnityEngine.VFXModule">
        <HintPath>..\..\..\.local\share\Steam\steamapps\common\Supermarket Together\Supermarket Together_Data\Managed\UnityEngine.VFXModule.dll</HintPath>
      </Reference>
      <Reference Include="UnityEngine.VideoModule">
        <HintPath>..\..\..\.local\share\Steam\steamapps\common\Supermarket Together\Supermarket Together_Data\Managed\UnityEngine.VideoModule.dll</HintPath>
      </Reference>
      <Reference Include="UnityEngine.VirtualTexturingModule">
        <HintPath>..\..\..\.local\share\Steam\steamapps\common\Supermarket Together\Supermarket Together_Data\Managed\UnityEngine.VirtualTexturingModule.dll</HintPath>
      </Reference>
      <Reference Include="UnityEngine.VRModule">
        <HintPath>..\..\..\.local\share\Steam\steamapps\common\Supermarket Together\Supermarket Together_Data\Managed\UnityEngine.VRModule.dll</HintPath>
      </Reference>
      <Reference Include="UnityEngine.WindModule">
        <HintPath>..\..\..\.local\share\Steam\steamapps\common\Supermarket Together\Supermarket Together_Data\Managed\UnityEngine.WindModule.dll</HintPath>
      </Reference>
      <Reference Include="UnityEngine.XRModule">
        <HintPath>..\..\..\.local\share\Steam\steamapps\common\Supermarket Together\Supermarket Together_Data\Managed\UnityEngine.XRModule.dll</HintPath>
      </Reference>
    </ItemGroup>
	
	<Target Name="PostBuild" AfterTargets="Build">
		<Copy SourceFiles="$(TargetPath)" DestinationFolder="/home/dia/.local/share/Steam/steamapps/common/Supermarket Together/BepInEx/plugins/" />
	</Target>

</Project>
